### GET REQUEST
GET http://127.0.0.1:8787/api HTTP/1.1
Content-Type: application/json

### GET BY ID
GET http://127.0.0.1:8787/api/4ce9cf37-5fd0-4622-b50c-f15fab61e9c6

### POST REQUEST
POST https://apinime.andresvp257.workers.dev/api
Content-Type: application/json

{
  "title": "Death Note",
    "year": 2006,
    "author": "Tsugumi Ohba",
    "episodes": 37,
    "rate": 8,
    "poster": "https://m.media-amazon.com/images/M/MV5BYTgyZDhmMTEtZDFhNi00MTc4LTg3NjUtYWJlNGE5Mzk2NzMxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "genre": ["Mystery", "Psychological", "Thriller"]
}

### DELETE REQUEST
DELETE http://127.0.0.1:8787/api/73a36adb-3243-43ab-a660-79e687bcb6ce

###PATCH REQUEST
PATCH http://127.0.0.1:8787/api/4ce9cf37-5fd0-4622-b50c-f15fab61e9c6
Content-Type: application/json

{
    "genre": [
      "Action",
      "Adventure",
      "Sci-Fi"
    ]
}